# Generated by Django 6.0.4 on 2026-04-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='login',
            new_name='username',
        ),
    ]
