# Generated by Django 6.0.4 on 2026-05-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_utilisateur_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hse',
            name='zoneIntervention',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ingenieur',
            name='matriculeTechnique',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ingenieur',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='legal',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
