# Generated by Django 6.0.4 on 2026-04-25 14:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('codeSite', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='S.Locality')),
                ('nomSite', models.CharField(default='', max_length=255, verbose_name='Name')),
                ('region', models.CharField(default='', max_length=100, verbose_name='Region')),
                ('wilaya', models.CharField(max_length=100, verbose_name='Wilaya')),
                ('commune', models.CharField(blank=True, max_length=100, null=True, verbose_name='Commune')),
                ('adresseSite', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='X')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Y')),
                ('typeSite', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type')),
                ('owner', models.CharField(blank=True, max_length=100, null=True, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'db_table': 'site',
            },
        ),
        migrations.CreateModel(
            name='Sinistre',
            fields=[
                ('idSinistre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nature', models.CharField(choices=[('FIBRE_OPTIQUE', 'Fibre Optique'), ('ACTE_DE_SABOTAGE', 'Acte de Sabotage'), ('VOL', 'Vol'), ('INCENDIE', 'Incendie'), ('INTEMPERIE', 'Intempérie'), ('CATASTROPHE_NATUREL', 'Catastrophe Naturel'), ('VIOLENCE_POLITIQUE', 'Violence Politique'), ('RC', 'RC')], max_length=30)),
                ('typeSinistre', models.CharField(choices=[('FIBRE_OPTIQUE', 'Fibre Optique'), ('ACTE_DE_SABOTAGE', 'Acte de Sabotage'), ('VOL', 'Vol'), ('VOL_PE', 'Vol + PE'), ('INCENDIE', 'Incendie'), ('INCENDIE_PE', 'Incendie + PE'), ('INCENDIE_SURTENSION_ELEC', 'Incendie Surtension Électrique'), ('VENT_VIOLENT', 'Vent Violent'), ('FOUDRE', 'Foudre'), ('PLUIE', 'Pluie'), ('TREMBLEMENT_DE_TERRE', 'Tremblement de Terre'), ('TEMPETE', 'Tempête'), ('INONDATION', 'Inondation'), ('GLISSEMENT_DE_TERRAIN', 'Glissement de Terrain'), ('DEGAT_DES_EAUX', 'Dégât des Eaux'), ('GREVES_EMEUTES', 'Grèves Émeutes'), ('MOUVEMENT_POPULAIRE', 'Mouvement Populaire'), ('AUTRES', 'Autres'), ('BRIS_DE_MACHINES', 'Bris de Machines'), ('BRIS_DE_GLACES', 'Bris de Glaces'), ('ACCIDENT_APPAREILS_ELEC', 'Accident aux Appareils Électriques'), ('RISQUES_INFORMATIQUES_ELEC', 'Risques Informatiques & Électroniques'), ('CHUTE_AERONEF_OBJET_SPATIAL', "Chute d'Aéronef ou Objet Spatial"), ('TRANSPORT_INTERNE', 'Transport Interne'), ('DOMMAGES', 'Dommages')], max_length=50)),
                ('dateSurvenance', models.DateField()),
                ('heureSurvenance', models.TimeField(blank=True, null=True)),
                ('descriptionDetailliee', models.TextField(blank=True, null=True)),
                ('montantEstime', models.FloatField(default=0.0)),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_EXPERTISE', 'En Expertise'), ('REJET_POUR_COMPLEMENT', 'Rejeté pour Complément'), ('EN_VALIDATION_LEGAL', 'En Validation Légale'), ('EN_VALIDATION_HSE', 'En Validation HSE'), ('TRANSMIS_ASSUREUR', "Transmis à l'Assureur"), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('CLOTURE', 'Clôturé'), ('ARCHIVE', 'Archivé')], default='OUVERT', max_length=30)),
                ('urgence', models.IntegerField(choices=[(1, 'Faible'), (2, 'Moyenne'), (3, 'Haute')], default=1)),
                ('dateCreation', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateCloture', models.DateTimeField(blank=True, null=True)),
                ('observationsIngenieur', models.TextField(blank=True, null=True, verbose_name="Observations de l'ingénieur")),
                ('numeroPV', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro PV de Police')),
                ('observationsLegal', models.TextField(blank=True, null=True, verbose_name='Observations du service légal')),
                ('observationsHSE', models.TextField(blank=True, null=True, verbose_name='Observations HSE')),
                ('mesuresCorrectives', models.TextField(blank=True, null=True, verbose_name='Mesures correctives proposées')),
                ('montantIndemnisation', models.FloatField(default=0.0, verbose_name="Montant d'indemnisation")),
                ('motifRejet', models.TextField(blank=True, null=True, verbose_name='Motif de rejet')),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sinistres_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créateur (Équipe Terrain)')),
                ('site', models.ForeignKey(db_column='codeSite', on_delete=django.db.models.deletion.PROTECT, related_name='sinistres', to='sinistres.site')),
            ],
            options={
                'verbose_name': 'Sinistre',
                'verbose_name_plural': 'Sinistres',
                'db_table': 'sinistre',
                'ordering': ['-dateCreation'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('idPiece', models.AutoField(primary_key=True, serialize=False)),
                ('titreDoc', models.CharField(max_length=255)),
                ('typePiece', models.CharField(choices=[('PHOTO_TERRAIN', 'Photo Terrain'), ('PV_POLICE', 'PV de Police'), ('RAPPORT_HSE', 'Rapport HSE'), ('RAPPORT_EXPERTISE', "Rapport d'Expertise"), ('DOCUMENT_ASSURANCE', 'Document Assurance'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='sinistres/attachments/')),
                ('dateUpload', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploadePar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_uploadees', to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
                ('sinistre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piecesJointes', to='sinistres.sinistre')),
            ],
            options={
                'verbose_name': 'Pièce Jointe',
                'verbose_name_plural': 'Pièces Jointes',
                'db_table': 'piece_jointe',
                'ordering': ['-dateUpload'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancienStatut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_EXPERTISE', 'En Expertise'), ('REJET_POUR_COMPLEMENT', 'Rejeté pour Complément'), ('EN_VALIDATION_LEGAL', 'En Validation Légale'), ('EN_VALIDATION_HSE', 'En Validation HSE'), ('TRANSMIS_ASSUREUR', "Transmis à l'Assureur"), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('CLOTURE', 'Clôturé'), ('ARCHIVE', 'Archivé')], max_length=30)),
                ('nouveauStatut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_EXPERTISE', 'En Expertise'), ('REJET_POUR_COMPLEMENT', 'Rejeté pour Complément'), ('EN_VALIDATION_LEGAL', 'En Validation Légale'), ('EN_VALIDATION_HSE', 'En Validation HSE'), ('TRANSMIS_ASSUREUR', "Transmis à l'Assureur"), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('CLOTURE', 'Clôturé'), ('ARCHIVE', 'Archivé')], max_length=30)),
                ('dateChangement', models.DateTimeField(default=django.utils.timezone.now)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('modifiePar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changements_statut', to=settings.AUTH_USER_MODEL)),
                ('sinistre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiqueStatuts', to='sinistres.sinistre')),
            ],
            options={
                'verbose_name': 'Historique de Statut',
                'verbose_name_plural': 'Historiques de Statut',
                'db_table': 'historique_statut',
                'ordering': ['-dateChangement'],
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('idEquipement', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nomMarque', models.CharField(max_length=100)),
                ('numeroSerie', models.CharField(blank=True, max_length=100, null=True)),
                ('dateInstallation', models.DateField(blank=True, null=True)),
                ('valeurComptable', models.FloatField(default=0.0)),
                ('quantiteImpactee', models.IntegerField(default=1)),
                ('sinistre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='sinistres.sinistre')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'db_table': 'equipement',
            },
        ),
    ]
