# Generated by Django 5.2.4 on 2026-04-18 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sinistre',
            fields=[
                ('idSinistre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nature', models.CharField(choices=[('FIBRE_OPTIQUE', 'Fibre Optique'), ('ACTE_DE_SABOTAGE', 'Acte de Sabotage'), ('VOL', 'Vol'), ('INCENDIE', 'Incendie'), ('INTEMPERIE', 'Intempérie'), ('CATASTROPHE_NATUREL', 'Catastrophe Naturel'), ('VIOLENCE_POLITIQUE', 'Violence Politique'), ('RC', 'RC')], max_length=30)),
                ('typeSinistre', models.CharField(choices=[('FIBRE_OPTIQUE', 'Fibre Optique'), ('ACTE_DE_SABOTAGE', 'Acte de Sabotage'), ('VOL', 'Vol'), ('VOL_PE', 'Vol + PE'), ('INCENDIE', 'Incendie'), ('INCENDIE_PE', 'Incendie + PE'), ('INCENDIE_SURTENSION_ELEC', 'Incendie Surtension Électrique'), ('VENT_VIOLENT', 'Vent Violent'), ('FOUDRE', 'Foudre'), ('PLUIE', 'Pluie'), ('TREMBLEMENT_DE_TERRE', 'Tremblement de Terre'), ('TEMPETE', 'Tempête'), ('INONDATION', 'Inondation'), ('GLISSEMENT_DE_TERRAIN', 'Glissement de Terrain'), ('DEGAT_DES_EAUX', 'Dégât des Eaux'), ('GREVES_EMEUTES', 'Grèves Émeutes'), ('MOUVEMENT_POPULAIRE', 'Mouvement Populaire'), ('AUTRES', 'Autres'), ('BRIS_DE_MACHINES', 'Bris de Machines'), ('BRIS_DE_GLACES', 'Bris de Glaces'), ('ACCIDENT_APPAREILS_ELEC', 'Accident aux Appareils Électriques'), ('RISQUES_INFORMATIQUES_ELEC', 'Risques Informatiques & Électroniques'), ('CHUTE_AERONEF_OBJET_SPATIAL', "Chute d'Aéronef ou Objet Spatial"), ('TRANSPORT_INTERNE', 'Transport Interne'), ('DOMMAGES', 'Dommages')], max_length=50)),
                ('dateSurvenance', models.DateField()),
                ('descriptionDetailliee', models.TextField(blank=True, null=True)),
                ('montantEstime', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Sinistre',
                'verbose_name_plural': 'Sinistres',
                'db_table': 'sinistre',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('idSite', models.AutoField(primary_key=True, serialize=False)),
                ('codeSite', models.CharField(max_length=50, unique=True)),
                ('adresseSite', models.CharField(max_length=255)),
                ('wilaya', models.CharField(max_length=100)),
                ('codeRegion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'db_table': 'site',
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('idPiece', models.AutoField(primary_key=True, serialize=False)),
                ('titreDoc', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('JPG', 'JPG'), ('PNG', 'PNG')], max_length=5)),
                ('urlFichier', models.CharField(max_length=500)),
                ('dateUpload', models.DateTimeField(default=django.utils.timezone.now)),
                ('tailleKo', models.BigIntegerField(default=0)),
                ('sinistre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piecesJointes', to='sinistres.sinistre')),
            ],
            options={
                'verbose_name': 'Pièce Jointe',
                'verbose_name_plural': 'Pièces Jointes',
                'db_table': 'piece_jointe',
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('idEquipement', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nomMarque', models.CharField(max_length=100)),
                ('numeroSerie', models.CharField(blank=True, max_length=100, null=True)),
                ('dateInstallation', models.DateField(blank=True, null=True)),
                ('valeurComptable', models.FloatField(default=0.0)),
                ('quantiteImpactee', models.IntegerField(default=1)),
                ('sinistre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='sinistres.sinistre')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'db_table': 'equipement',
            },
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('idDeclaration', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('dateCreation', models.DateTimeField(default=django.utils.timezone.now)),
                ('etatActuel', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20)),
                ('urgence', models.IntegerField(choices=[(1, 'Faible'), (2, 'Moyenne'), (3, 'Haute')], default=1)),
                ('sinistre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declaration', to='sinistres.sinistre')),
            ],
            options={
                'verbose_name': 'Déclaration',
                'verbose_name_plural': 'Déclarations',
                'db_table': 'declaration',
            },
        ),
        migrations.AddField(
            model_name='sinistre',
            name='site',
            field=models.ForeignKey(db_column='codeSite', on_delete=django.db.models.deletion.PROTECT, related_name='sinistres', to='sinistres.site', to_field='codeSite'),
        ),
    ]
