# Generated by Django 6.0.4 on 2026-05-02 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistres', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquestatut',
            name='ancienStatut',
            field=models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_EXPERTISE', 'En Expertise'), ('REJET_POUR_COMPLEMENT', 'Rejeté pour Complément'), ('EN_VALIDATION_LEGAL', 'En Validation Légale'), ('EN_VALIDATION_HSE', 'En Validation HSE'), ('TRANSMIS_ASSUREUR', "Transmis à l'Assureur"), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('CLOTURE', 'Clôturé'), ('CLOTURE_SOUS_FRANCHISE', 'Clôturé — Sous Franchise'), ('ARCHIVE', 'Archivé')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historiquestatut',
            name='nouveauStatut',
            field=models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_EXPERTISE', 'En Expertise'), ('REJET_POUR_COMPLEMENT', 'Rejeté pour Complément'), ('EN_VALIDATION_LEGAL', 'En Validation Légale'), ('EN_VALIDATION_HSE', 'En Validation HSE'), ('TRANSMIS_ASSUREUR', "Transmis à l'Assureur"), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('CLOTURE', 'Clôturé'), ('CLOTURE_SOUS_FRANCHISE', 'Clôturé — Sous Franchise'), ('ARCHIVE', 'Archivé')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='statut',
            field=models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_EXPERTISE', 'En Expertise'), ('REJET_POUR_COMPLEMENT', 'Rejeté pour Complément'), ('EN_VALIDATION_LEGAL', 'En Validation Légale'), ('EN_VALIDATION_HSE', 'En Validation HSE'), ('TRANSMIS_ASSUREUR', "Transmis à l'Assureur"), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('CLOTURE', 'Clôturé'), ('CLOTURE_SOUS_FRANCHISE', 'Clôturé — Sous Franchise'), ('ARCHIVE', 'Archivé')], default='OUVERT', max_length=30),
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('FIBRE_OPTIQUE', 'Fibre Optique'), ('ACTE_DE_SABOTAGE', 'Acte de Sabotage'), ('VOL', 'Vol'), ('INCENDIE', 'Incendie'), ('INTEMPERIE', 'Intempérie'), ('CATASTROPHE_NATUREL', 'Catastrophe Naturel'), ('VIOLENCE_POLITIQUE', 'Violence Politique'), ('RC', 'RC')], max_length=30, unique=True)),
                ('montant', models.FloatField(default=0.0, verbose_name='Montant de la franchise (DA)')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='franchises_modifiees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Franchise',
                'verbose_name_plural': 'Franchises',
                'db_table': 'franchise',
            },
        ),
    ]
