# Generated by Django 6.0.4 on 2026-05-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistres', '0003_alter_historiquestatut_ancienstatut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquestatut',
            name='ancienStatut',
            field=models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_EXPERTISE', 'En Expertise'), ('REJET_POUR_COMPLEMENT', 'Rejeté pour Complément'), ('EN_VALIDATION_LEGAL', 'En Validation Légale'), ('EN_VALIDATION_HSE', 'En Validation HSE'), ('TRANSMIS_ASSUREUR', "Transmis à l'Assureur"), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('CLOTURE', 'Clôturé'), ('ATTENTE_VALIDATION_FRANCHISE', 'En Attente de Clôture (Sous Franchise)'), ('CLOTURE_SOUS_FRANCHISE', 'Clôturé — Sous Franchise'), ('ARCHIVE', 'Archivé')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historiquestatut',
            name='nouveauStatut',
            field=models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_EXPERTISE', 'En Expertise'), ('REJET_POUR_COMPLEMENT', 'Rejeté pour Complément'), ('EN_VALIDATION_LEGAL', 'En Validation Légale'), ('EN_VALIDATION_HSE', 'En Validation HSE'), ('TRANSMIS_ASSUREUR', "Transmis à l'Assureur"), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('CLOTURE', 'Clôturé'), ('ATTENTE_VALIDATION_FRANCHISE', 'En Attente de Clôture (Sous Franchise)'), ('CLOTURE_SOUS_FRANCHISE', 'Clôturé — Sous Franchise'), ('ARCHIVE', 'Archivé')], max_length=30),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='statut',
            field=models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_EXPERTISE', 'En Expertise'), ('REJET_POUR_COMPLEMENT', 'Rejeté pour Complément'), ('EN_VALIDATION_LEGAL', 'En Validation Légale'), ('EN_VALIDATION_HSE', 'En Validation HSE'), ('TRANSMIS_ASSUREUR', "Transmis à l'Assureur"), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('CLOTURE', 'Clôturé'), ('ATTENTE_VALIDATION_FRANCHISE', 'En Attente de Clôture (Sous Franchise)'), ('CLOTURE_SOUS_FRANCHISE', 'Clôturé — Sous Franchise'), ('ARCHIVE', 'Archivé')], default='OUVERT', max_length=30),
        ),
    ]
