# Generated by Django 6.0.4 on 2026-05-04 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistres', '0005_notification_expediteur_notification_sinistre_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='sinistre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='sinistres.sinistre'),
        ),
    ]
