# Generated by Django 6.0.4 on 2026-05-06 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistres', '0006_alter_equipement_sinistre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinistre',
            name='site',
            field=models.ForeignKey(blank=True, db_column='codeSite', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sinistres', to='sinistres.site'),
        ),
    ]
